# Generated by Django 2.2 on 2020-11-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=200)),
                ('planet_size', models.CharField(max_length=200)),
                ('planet_attributes', models.CharField(max_length=200)),
                ('planet_location', models.CharField(max_length=200)),
            ],
        ),
    ]
