# Generated by Django 2.2 on 2020-11-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SolarModel', '0003_auto_20201126_1028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planet',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='planet_age',
            new_name='item_age',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='planet_characteristics',
            new_name='item_characteristics',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='planet_distance',
            new_name='item_distance',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='planet_mass',
            new_name='item_mass',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='planet_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='planet_size',
            new_name='item_size',
        ),
    ]
