# Generated by Django 2.2 on 2020-11-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarModel', '0004_auto_20201130_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='background_image',
            field=models.ImageField(default='space.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_characteristics',
            field=models.CharField(max_length=500),
        ),
    ]
