# Generated by Django 2.2 on 2020-11-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarModel', '0005_auto_20201130_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='background_image',
            field=models.ImageField(default='images/space.png', upload_to=''),
        ),
    ]
