# Generated by Django 2.2 on 2020-12-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarModel', '0006_auto_20201130_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='background_image',
            field=models.ImageField(default="https://i0.wp.com/dotsandlines.steveboerner.com/wp-content/uploads/2016/06/earth_planet_600x300.jpg?resize=600%2C400'", upload_to=''),
        ),
    ]
