# Generated by Django 2.2 on 2020-12-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarModel', '0007_auto_20201201_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='background_image',
            field=models.ImageField(default='https://www.takeoutlist.com/assets/images/food_default.png', upload_to=''),
        ),
    ]
