# Generated by Django 2.2 on 2020-12-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarModel', '0008_auto_20201201_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='background_image',
            field=models.CharField(default='https://www.takeoutlist.com/assets/images/food_default.png', max_length=500),
        ),
    ]
